### ISSUE TITLE
MTDA C-driving model core directory

### ISSUE THREAD

**Issue by jnikhilreddy** [liuyunan19910713/Domain-adaptive-semantic-segmentation#1]
Congratulations on NeurIPS 2021 paper(link) acceptance. Thanks for posting the code and models for the NeurIPS2021 paper. 
I was trying out the test_vgg.py  code on the MTDA C-driving model folder. In the code, it uses a core directory but there is no such directory in the code.
Can you give pointers on how to run the code in the GitHub link?

**Comment by Anony123lyn** [comment]
Thank you for your attention! We have uploaded the missing folders.
